name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/2e2

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.16.0-chrome-112.0.5615.121-1-ff-112.0.1-edge-112.0.1722.48-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.2
      - name: Cypress run
        uses: cypress-io/github-action@v5.7.1
        with:
          install-command: npm install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: e6830655-0714-481e-b7fe-1cd5fbd4d3bd
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-electron-chrome:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.16.0-chrome-112.0.5615.121-1-ff-112.0.1-edge-112.0.1722.48-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.2
      - name: Cypress run
        uses: cypress-io/github-action@v5.7.1
        with:
          install-command: npm install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: e6830655-0714-481e-b7fe-1cd5fbd4d3bd
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-electron-firefox:
    needs: cypress-electron-chrome
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.16.0-chrome-112.0.5615.121-1-ff-112.0.1-edge-112.0.1722.48-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.2
      - name: Cypress run
        uses: cypress-io/github-action@v5.7.1
        with:
          install-command: npm install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
    env:
          CYPRESS_RECORD_KEY: e6830655-0714-481e-b7fe-1cd5fbd4d3bd
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
          
     
